### ISSUE TITLE
Look in to Atlas for MongoDB

### ISSUE THREAD

**Issue by kingdomlevel** [kingdomlevel/toast#7]
I don't know  a great deal about this but it sounds like a good idea ☺️

**Comment by PorcelainAddict** [comment]
Looking into MongoDb Atlas could be an actual shout btw. As it would mean that we wouldn't have to run a DB locally for song in dev? Looking into it and it is pretty simple to set up. Would need to work out a config setting, and also local .env files but that would simply be for a process.env.MONGOPASSCODEOFTHEGODS << taking liberties with the name. 
![Screenshot 2021-01-20 at 17 51 49](https://user-images.githubusercontent.com/57002969/105214939-8d389280-5b48-11eb-93a3-0de3d5e5ddf5.png)

**Comment by kingdomlevel** [comment]
yoooo this looks class! would we need an Atlas account / is it all free etc?

I think if it looks good I'm up for going ahead w this, and we could just turn this issue from research > enhancement and implement the DB here?

Any other thoughts on this?

**Comment by PorcelainAddict** [comment]
I had a look into it aaaaaand the screenshot is my account. However I can add projects, and then invite collaborators which would make the mgmt way easier. Additionally it is *FREE* !! That's right FREE, with no deposit down! There's a choice of servers, so would just choose Ireland 🇮🇪  (for some reason I have chosen N. Virginia??)

**Comment by kingdomlevel** [comment]
We discussed this on a wee call today and are going to try and go ahead w it! @PorcelainAddict to lead on it 💪
